# Site
#repository: 
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Rodolfo Capellini
title: Desenvolvimento Full Stack
email: rodolfocapelline@gmail.com
phone: (14) - 99777-7195
website: 

# Social links
twitter_username: 
github_username:  
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: rodolfocapelline
linkedin_username: rodolfo-capelline-172057b4
xing_username: 
pinterest_username: 
youtube_username: 
googleplus_username: 

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/me.jpeg
about_content: | # this will include new lines to allow paragraphs
 Olá meu nome é Rodolfo, conhecido como Dorfo, sou desenvolvedor full Stack, tenho experiência nas tecnologias mais novas com as quais trabalho diariamente.

  Skills
    - PHP
    - NodeJs
    - Angular
    - React
    - MongoDB
    - MySql
    - Redis

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Agora falando um pouco mais sobre mim, minhas paixões são, minha companheira(esposa) e minhas cachorras. Meus hobbies são, fazer trilhas, andar de moto e comer pizza.
  *Alguns cursos extras*
    - Scrum Foundation Professional Certificate - (Portuguese);
    - Curso Desenvolvimento Mobile (Android) Caelum;
    - Curso Complementar Magento Commerce;
    - Curso Complementar CCNA Exploration Network Fundamentals;
    - Curso Complementar Fundamentos do Entity Framework 4;
    - Curso Complementar Fundamentos do Desenvolvimento de Software;
    - Curso Complementar HTML5 – Homologado pelo W3C;

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
