# Site
#repository: 
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Rodolfo Capellini
title: Desenvolvedor
email: rodolfocapelline@gmail.com
phone: (14) - 99777-7195
website: 

# Social links
twitter_username: 
github_username:  
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: rodolfocapelline
linkedin_username: rodolfo-capellini
xing_username: 
pinterest_username: 
youtube_username: 
googleplus_username: 

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/me.jpeg
about_content: | # this will include new lines to allow paragraphs
  Saudações, meu nome é Rodolfo, embora seja mais conhecido como Dorfo. Sou um profissional de desenvolvimento e tenho como objetivo utilizar a tecnologia de maneira eficaz para resolver desafios e simplificar a vida das pessoas.

  Minhas habilidades incluem:
    - PHP
    - Node.js
    - .Net C#
    - Angular
    - MongoDB
    - MySQL
    - PostgreSQL
    - Redis

  Estou comprometido em aplicar essas competências para criar soluções inovadoras e melhorar a experiência tecnológica em diversos contextos.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Agora, compartilhando um pouco mais sobre mim, minhas paixões incluem minha esposa, minhas três adoráveis cachorras e meus cinco gatos - tenho um profundo amor pelos animais. Quanto aos meus hobbies, gosto de explorar trilhas na natureza, viajar para novos lugares e desfrutar de uma boa pizza.

  *Alguns cursos extras*
    - TDD com xUnit para C# .NET Core
    - Fundamentos de Arquitetura de Microsserviços (Microservices)
    - Clean Architecture Essencial - ASP .NET Core com C#
    - NodeJs, Typescript, TDD, DDD, Clean Architecture e SOLID
    - NodeJs Avançado com TDD, Clean Architecture e Typescript
    - Scrum Foundation Professional Certificate - (Portuguese);
    - Curso Desenvolvimento Mobile (Android) Caelum;
    - Curso Complementar Magento Commerce;
    - Curso Complementar CCNA Exploration Network Fundamentals;
    - Curso Complementar Fundamentos do Entity Framework 4;
    - Curso Complementar Fundamentos do Desenvolvimento de Software;
    - Curso Complementar HTML5 – Homologado pelo W3C;

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
